services:
    PoP\Media\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Media\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
